[project]
name = "pyleetcode"
version = "0.1.0"
description = "Python uv project for maintaining my data structures and algorithms knowledge"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]
